"""Dashboard row status in Postgres (configuration vs frozen)."""

DASHBOARD_DRAFT = "draft"
DASHBOARD_FROZEN = "frozen"
DASHBOARD_INACTIVE = "inactive"
DASHBOARD_ARCHIVED = "archived"

DASHBOARD_STATUSES = (DASHBOARD_DRAFT, DASHBOARD_FROZEN, DASHBOARD_INACTIVE, DASHBOARD_ARCHIVED)
